const fs = require('node:fs');
const path = require('node:path');

const sourcePath = path.resolve(__dirname, '../../../packages/app-host/src/preload-api.cjs');
const outputPath = path.resolve(__dirname, '../preload.cjs');

function preloadBundle(source = fs.readFileSync(sourcePath, 'utf8')) {
  return `// Generated by scripts/prepare-preload.cjs. Edit packages/app-host/src/preload-api.cjs instead.
const { createAppPreloadApi } = (() => {
  const module = { exports: {} };
${source}
  return module.exports;
})();
const { contextBridge, ipcRenderer, webUtils } = require('electron');
contextBridge.exposeInMainWorld('live2pet', createAppPreloadApi({
  ipcRenderer,
  getFilePath: (file) => webUtils.getPathForFile(file),
}));
`;
}

function preparePreload(output = outputPath) {
  fs.mkdirSync(path.dirname(output), { recursive: true });
  fs.writeFileSync(output, preloadBundle());
  return output;
}

if (require.main === module) process.stdout.write(`${preparePreload()}\n`);
module.exports = { preloadBundle, preparePreload };
