// Generated by scripts/prepare-preload.cjs. Edit packages/app-host/src/preload-api.cjs instead.
const { createAppPreloadApi } = (() => {
  const module = { exports: {} };
// One dependency-free implementation for the sandboxed Desktop preload and Node tests.
const APP_COMMANDS = Object.freeze(['new', 'open', 'save', 'settings', 'build', 'setup', 'undo', 'redo']);

function createAppPreloadApi({ ipcRenderer, channel = 'live2pet:app', getFilePath: resolveNativeFilePath = null } = {}) {
  if (!ipcRenderer || typeof ipcRenderer.invoke !== 'function') throw new TypeError('App preload requires ipcRenderer.invoke.');
  if (typeof channel !== 'string' || !channel.trim()) throw new TypeError('App preload requires a non-empty channel.');
  const APP_IPC_CHANNEL = channel;
  const APP_BUILD_PROGRESS_CHANNEL = 'live2pet:build-progress';
  const APP_LIBRARY_DOWNLOAD_PROGRESS_CHANNEL = 'live2pet:library-download-progress';
  const APP_COMMAND_CHANNEL = 'live2pet:command';
  const PREVIEW_IPC_CHANNEL = 'live2pet:preview';
  const PREVIEW_STATUS_CHANNEL = 'live2pet:preview-status';
  const APP_IPC_PROTOCOL_VERSION = 1;
  const BUILD_PROGRESS_FIELDS = [
    'requestId', 'projectId', 'snapshotFingerprint',
    'target', 'stage', 'status', 'motionId', 'name', 'width', 'height', 'samples', 'duration',
    'total', 'completed', 'index', 'frameCount', 'concurrency', 'percent', 'fraction', 'message',
    'error',
    'motions', 'assets', 'states', 'reactions', 'rows', 'cells', 'occupiedCells',
    'transparentCells', 'cache', 'cacheHits', 'cacheMisses', 'ready', 'missingStates',
    'missingReactions', 'format', 'byteLength', 'packageByteLength', 'previewReady',
  ];
  const invoke = (method, ...args) => ipcRenderer.invoke(APP_IPC_CHANNEL, {
    protocolVersion: APP_IPC_PROTOCOL_VERSION,
    method,
    args,
  });
  const invokePreview = (method, input) => ipcRenderer.invoke(PREVIEW_IPC_CHANNEL, {
    protocolVersion: APP_IPC_PROTOCOL_VERSION,
    method,
    ...(input === undefined ? {} : { input }),
  });
  const normalizeBuildProgressPayload = (payload) => {
    if (!payload || typeof payload !== 'object' || Array.isArray(payload)) return null;
    if (payload.protocolVersion !== APP_IPC_PROTOCOL_VERSION || typeof payload.buildId !== 'string' || !payload.buildId.trim() || !Number.isInteger(payload.sequence) || payload.sequence < 1) return null;
    if (typeof payload.stage !== 'string' || !payload.stage.trim() || typeof payload.status !== 'string' || !payload.status.trim()) return null;
    const normalized = { protocolVersion: APP_IPC_PROTOCOL_VERSION, buildId: payload.buildId.slice(0, 128), sequence: payload.sequence, stage: payload.stage.trim().slice(0, 64), status: payload.status.trim().slice(0, 64) };
    for (const key of BUILD_PROGRESS_FIELDS) {
      if (!Object.hasOwn(payload, key)) continue;
      const value = payload[key];
      if (typeof value === 'string' && value.length <= 256 && !/^(?:\/|[A-Za-z]:[\\/]|\\\\)/.test(value)) normalized[key] = value;
      else if (typeof value === 'number' && Number.isFinite(value)) normalized[key] = value;
      else if (typeof value === 'boolean') normalized[key] = value;
      else if (Array.isArray(value) && value.length <= 64 && value.every((item) => (typeof item === 'string' && item.length <= 256 && !/^(?:\/|[A-Za-z]:[\\/]|\\\\)/.test(item)) || (typeof item === 'number' && Number.isFinite(item)) || typeof item === 'boolean')) normalized[key] = [...value];
    }
    if (payload.stageFractions && typeof payload.stageFractions === 'object' && !Array.isArray(payload.stageFractions)) {
      const fractions = Object.fromEntries(['capture', 'validate', 'encode']
        .filter(key => Object.hasOwn(payload.stageFractions, key) && Number.isFinite(payload.stageFractions[key]))
        .map(key => [key, Math.max(0, Math.min(1, payload.stageFractions[key]))]));
      if (Object.keys(fractions).length) normalized.stageFractions = fractions;
    }
    return normalized;
  };
  const onBuildProgress = (listener) => {
    if (typeof listener !== 'function') throw new TypeError('onBuildProgress requires a function listener.');
    const handler = (_event, payload) => {
      const normalized = normalizeBuildProgressPayload(payload);
      if (normalized) listener(Object.freeze(normalized));
    };
    ipcRenderer.on(APP_BUILD_PROGRESS_CHANNEL, handler);
    let active = true;
    return () => {
      if (!active) return;
      active = false;
      ipcRenderer.removeListener(APP_BUILD_PROGRESS_CHANNEL, handler);
    };
  };
  const normalizeLibraryDownloadProgressPayload = (payload) => {
    if (!payload || typeof payload !== 'object' || Array.isArray(payload) || payload.protocolVersion !== APP_IPC_PROTOCOL_VERSION) return null;
    if (typeof payload.downloadId !== 'string' || !/^[A-Za-z0-9_-]{8,128}$/.test(payload.downloadId) || !Number.isInteger(payload.sequence) || payload.sequence < 1) return null;
    if (typeof payload.libraryId !== 'string' || !/^[A-Za-z0-9_-]{8,128}$/.test(payload.libraryId) || !['downloading', 'complete'].includes(payload.stage)) return null;
    for (const key of ['total', 'completed', 'downloaded', 'cached', 'failed', 'percent']) if (!Number.isInteger(payload[key]) || payload[key] < 0 || (key === 'percent' ? payload[key] > 100 : payload[key] > 512)) return null;
    if (payload.completed > payload.total || payload.downloaded + payload.cached + payload.failed > payload.completed) return null;
    if (payload.currentName !== undefined && (typeof payload.currentName !== 'string' || !payload.currentName.trim() || payload.currentName.length > 256 || /^(?:\/|[A-Za-z]:[\\/]|\\\\)/.test(payload.currentName))) return null;
    return { protocolVersion: APP_IPC_PROTOCOL_VERSION, downloadId: payload.downloadId, sequence: payload.sequence, libraryId: payload.libraryId, stage: payload.stage, total: payload.total, completed: payload.completed, downloaded: payload.downloaded, cached: payload.cached, failed: payload.failed, percent: payload.percent, ...(payload.currentName ? { currentName: payload.currentName.trim() } : {}) };
  };
  const onLibraryDownloadProgress = (listener) => {
    if (typeof listener !== 'function') throw new TypeError('onLibraryDownloadProgress requires a function listener.');
    const handler = (_event, payload) => {
      const normalized = normalizeLibraryDownloadProgressPayload(payload);
      if (normalized) listener(Object.freeze(normalized));
    };
    ipcRenderer.on(APP_LIBRARY_DOWNLOAD_PROGRESS_CHANNEL, handler);
    let active = true;
    return () => {
      if (!active) return;
      active = false;
      ipcRenderer.removeListener(APP_LIBRARY_DOWNLOAD_PROGRESS_CHANNEL, handler);
    };
  };
  const onAppCommand = (listener) => {
    if (typeof listener !== 'function') throw new TypeError('onAppCommand requires a function listener.');
    const handler = (_event, command) => {
      if (APP_COMMANDS.includes(command)) listener(command);
    };
    ipcRenderer.on(APP_COMMAND_CHANNEL, handler);
    let active = true;
    return () => {
      if (!active) return;
      active = false;
      ipcRenderer.removeListener(APP_COMMAND_CHANNEL, handler);
    };
  };
  const getFilePath = (file) => {
    if (typeof resolveNativeFilePath !== 'function') return null;
    try {
      const value = resolveNativeFilePath(file);
      return typeof value === 'string' && value ? value : null;
    } catch {
      return null;
    }
  };
  const onPreviewStatus = (listener) => {
    if (typeof listener !== 'function') throw new TypeError('onPreviewStatus requires a function listener.');
    const handler = (_event, payload) => {
      if (!payload || typeof payload !== 'object' || payload.schemaVersion !== 1 || !['idle', 'opening', 'ready', 'failed'].includes(payload.state)) return;
      listener(Object.freeze(payload));
    };
    ipcRenderer.on(PREVIEW_STATUS_CHANNEL, handler);
    let active = true;
    return () => {
      if (!active) return;
      active = false;
      ipcRenderer.removeListener(PREVIEW_STATUS_CHANNEL, handler);
    };
  };

  return Object.freeze({
    getVersion: () => invoke('getVersion'),
    checkForUpdates: () => invoke('checkForUpdates'),
    openReleasePage: (version) => invoke('openReleasePage', { version }),
    getRecentProjects: () => invoke('getRecentProjects'),
    clearRecentProjects: () => invoke('clearRecentProjects', { confirmClear: true }),
    openProject: (input = {}) => invoke('openProject', input),
    saveProject: (input) => invoke('saveProject', input),
    openSourceLibrary: (inputPath) => inputPath ? invoke('openSourceLibrary', { inputPath }) : invoke('openSourceLibrary'),
    openGitHubLibrary: (url) => invoke('openGitHubLibrary', { url }),
    downloadSourceLibrary: (libraryId) => invoke('downloadSourceLibrary', { libraryId }),
    inspectLibrarySource: (input) => invoke('inspectLibrarySource', input),
    getLibraryThumbnail: (input) => invoke('getLibraryThumbnail', input),
    getSourceLibraryCacheStatus: () => invoke('getSourceLibraryCacheStatus'),
    configureSourceLibraryCache: (maxBytes) => invoke('configureSourceLibraryCache', { maxBytes }),
    clearSourceLibraryCache: () => invoke('clearSourceLibraryCache', { confirmClear: true }),
    onLibraryDownloadProgress,
    onAppCommand,
    inspectSource: (input) => invoke('inspectSource', input),
    relinkSource: (input) => invoke('relinkSource', input),
    acknowledgeSourceReview: (input) => invoke('acknowledgeSourceReview', input),
    getRuntimeSettings: () => invoke('getRuntimeSettings'),
    configureRuntime: (input) => invoke('configureRuntime', input),
    clearRuntimeSettings: (input) => input === undefined ? invoke('clearRuntimeSettings') : invoke('clearRuntimeSettings', input),
    getSpinePackStatus: () => invoke('getSpinePackStatus'),
    installSpinePack: (runtimeLine) => invoke('installSpinePack', { confirmInstall: true, runtimeLine }),
    removeSpinePack: (runtimeLine) => invoke('removeSpinePack', { runtimeLine }),
    getCaptureCacheStatus: (input) => invoke('getCaptureCacheStatus', input),
    putCaptureCache: (input) => invoke('putCaptureCache', input),
    getBuildCacheStatus: () => invoke('getBuildCacheStatus'),
    clearBuildCache: (input) => invoke('clearBuildCache', input),
    getFilePath,
    buildProject: (input) => invoke('buildProject', input),
    cancelBuild: (buildId) => invoke('cancelBuild', { buildId }),
    onBuildProgress,
    getBuildArtifact: (artifactId, offset = 0) => invoke('getBuildArtifact', { artifactId, offset }),
    getOutputSettings: () => invoke('getOutputSettings'),
    configureOutputSettings: (input) => invoke('configureOutputSettings', input),
    saveBuildArtifact: (artifactId) => invoke('saveBuildArtifact', { artifactId }),
    chooseInstallRoot: (target) => invoke('chooseInstallRoot', { target }),
    getTargetInstallations: () => invoke('getTargetInstallations'),
    configureTargetInstallation: (input) => invoke('configureTargetInstallation', input),
    installArtifact: (request) => invoke('installArtifact', request),
    openPreview: (input) => invokePreview('open', input),
    layoutPreview: (input) => invokePreview('layout', input),
    playPreview: (input) => invokePreview('play', input),
    setPreviewExpression: (input) => invokePreview('setExpression', input),
    getPreviewVisualElements: () => invokePreview('getVisualElements'),
    getPreviewVisualElementThumbnail: (input) => invokePreview('getVisualElementThumbnail', input),
    scanPreviewVisualElements: (input) => invokePreview('scanVisualElements', input),
    setPreviewVisualSettings: (input) => invokePreview('setVisualSettings', input),
    controlPreview: (input) => invokePreview('control', input),
    closePreview: () => invokePreview('close'),
    getPreviewStatus: () => invokePreview('getStatus'),
    onPreviewStatus,
  });
}

module.exports = { createAppPreloadApi, APP_COMMANDS };

  return module.exports;
})();
const { contextBridge, ipcRenderer, webUtils } = require('electron');
contextBridge.exposeInMainWorld('live2pet', createAppPreloadApi({
  ipcRenderer,
  getFilePath: (file) => webUtils.getPathForFile(file),
}));
