const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');

const root = path.resolve(__dirname, '..');

test('desktop shell pins the mapper entrypoint and keeps navigation and IPC narrow', () => {
  const main = fs.readFileSync(path.join(root, 'main.cjs'), 'utf8');
  const preload = fs.readFileSync(path.join(root, 'preload.cjs'), 'utf8');
  assert.match(main, /const DEVELOPMENT_MAPPER_PATH = path\.resolve\(__dirname, '\.\.\/mapper\/index\.html'\);/);
  assert.match(main, /const PACKAGED_MAPPER_PATH = path\.join\(process\.resourcesPath, 'mapper-dist', 'index\.html'\);/);
  assert.match(main, /return app\.isPackaged \? PACKAGED_MAPPER_PATH : DEVELOPMENT_MAPPER_PATH;/);
  assert.match(main, /loadRuntimeForGeneration/);
  assert.match(main, /protocol\.registerSchemesAsPrivileged/);
  assert.match(main, /defaultSession\.protocol\.handle\(RUNTIME_PROTOCOL_SCHEME/);
  assert.match(main, /createRuntimeProtocolHandler/);
  assert.match(main, /buildProjectService: buildProjectWithCaptureCache/);
  assert.match(main, /getCaptureCacheService/);
  assert.match(main, /getCaptureCacheStore/);
  assert.match(main, /getEncodedCache: getCaptureCacheStore/);
  assert.doesNotMatch(main, /MapperSession|rendererPreview|SKILL_PATH|skillService|installSkill/);
  assert.match(main, /APP_BUILD_PROGRESS_CHANNEL/);
  assert.match(main, /webContents\.send\(APP_BUILD_PROGRESS_CHANNEL/);
  assert.match(main, /installPackageService: installPackage/);
  assert.match(main, /installRootPickerService: chooseInstallRoot/);
  assert.match(main, /dialog\.showOpenDialog/);
  assert.match(main, /event\.sender !== mainWindow\.webContents/);
  assert.match(main, /setWindowOpenHandler\(\(\) => \(\{ action: 'deny' \}\)\)/);
  assert.match(main, /mainWindow\.once\('ready-to-show', showWindow\);[\s\S]*await mainWindow\.loadFile\(documentPath\);[\s\S]*!mainWindow\.isVisible\(\)/);
  assert.match(main, /APP_BUNDLE_SMOKE_ARGUMENT = '--live2pet-smoke-test'/);
  assert.match(main, /LIVE2PET_BUNDLE_READY/);
  assert.match(main, /webContents\.on\('will-navigate'/);
  assert.match(main, /webContents\.on\('will-attach-webview'/);
  assert.match(main, /setPermissionRequestHandler/);
  assert.match(main, /setPermissionCheckHandler/);
  assert.doesNotMatch(main, /nodeIntegration:\s*true/);
  assert.match(preload, /contextBridge\.exposeInMainWorld\('live2pet'/);
  assert.match(preload, /const APP_IPC_CHANNEL = 'live2pet:app';/);
  assert.match(preload, /const APP_IPC_PROTOCOL_VERSION = 1;/);
  assert.match(preload, /const APP_BUILD_PROGRESS_CHANNEL = 'live2pet:build-progress';/);
  assert.match(preload, /webUtils\.getPathForFile/);
  assert.match(preload, /getFilePath,/);
  for (const method of ['getVersion', 'inspectSource', 'getRuntimeSettings', 'configureRuntime', 'clearRuntimeSettings', 'buildProject', 'cancelBuild', 'getBuildArtifact', 'chooseInstallRoot', 'installArtifact', 'getCaptureCacheStatus', 'putCaptureCache', 'getBuildCacheStatus', 'clearBuildCache']) {
    assert.match(preload, new RegExp(`invoke\\('${method}'`));
  }
  assert.doesNotMatch(preload, /MapperSession|RendererPreview|getSkillStatus|installSkill|rendererCommand/);
  assert.match(preload, /getBuildArtifact: \(artifactId, offset = 0\) => invoke\('getBuildArtifact', \{ artifactId, offset \}\)/);
  assert.match(main, /webContents\.on\('render-process-gone'/);
  assert.match(preload, /onBuildProgress/);
  assert.doesNotMatch(preload, /require\(['"]\.\.\/\.\.\/packages\/app-host/);
  assert.doesNotMatch(preload, /exposeInMainWorld\([^,]+,\s*\{\s*ipcRenderer/);
});

test('desktop removes deferred Skill, Mapper Session, and separate-preview entrypoints', () => {
  for (const relative of ['renderer/index.html', 'renderer-preload.cjs', 'renderer-host.cjs', 'renderer-preview-service.cjs']) {
    assert.equal(fs.existsSync(path.join(root, relative)), false, `${relative} should not ship in V1`);
  }
});

test('desktop package keeps Electron and future Forge settings explicit', () => {
  const manifest = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
  const forge = fs.readFileSync(path.join(root, 'forge.config.cjs'), 'utf8');
  assert.equal(manifest.devDependencies.electron, '44.0.0');
  assert.equal(manifest.devDependencies['@electron/packager'], '20.3.0');
  assert.equal(manifest.scripts.start, 'electron .');
  assert.equal(manifest.scripts['package:mac'], 'node scripts/stage-mapper-assets.cjs && node scripts/package-macos.cjs');
  assert.equal(manifest.scripts['smoke:mac'], 'node scripts/smoke-packaged-app.cjs');
  assert.match(forge, /asar:\s*\{\s*unpack:\s*'\*\*\/node_modules\/\{sharp,@img\}\/\*\*\/\*'\s*\}/);
  assert.match(forge, /executableName:\s*'live2pet'/);
  assert.match(forge, /extraResource:\s*\[path\.resolve\(__dirname, 'mapper-dist'\)\]/);
  assert.doesNotMatch(forge, /live2pet-skill|renderer\.html/);
  assert.equal(manifest.scripts['prepare:mapper'], 'node scripts/stage-mapper-assets.cjs');
});

test('shared Mapper uses the App build seam when available and keeps browser fallback intact', () => {
  const mapper = fs.readFileSync(path.resolve(root, '../mapper/index.html'), 'utf8');
  assert.match(mapper, /function desktopBuildApi\(\)/);
  assert.match(mapper, /window\.live2pet\.buildProject/);
  assert.match(mapper, /window\.live2pet\.getBuildArtifact/);
  assert.match(mapper, /window\.live2pet\.installArtifact/);
  assert.match(mapper, /optionsByTarget: \{ "codex-pet": \{ package: true/);
  assert.match(mapper, /if \(desktopArtifact\) \{/);
  assert.match(mapper, /Encoding transparent WebP atlas/);
  assert.match(mapper, /function buildClawdThroughDesktop\(project, framesByMotion, captureCache, signal = null\)/);
  assert.match(mapper, /optionsByTarget: \{ clawd: \{ package: true/);
  assert.match(mapper, /id="buildClawd"/);
  assert.match(mapper, /id="downloadClawd"/);
  assert.match(mapper, /id="refreshBuildCache"/);
  assert.match(mapper, /id="clearBuildCache"/);
  assert.match(mapper, /getBuildCacheStatus/);
  assert.match(mapper, /clearBuildCache\(\{ confirmClear: true \}\)/);
  assert.match(mapper, /cache\.status\.ready/);
  assert.match(mapper, /inputsByTarget: \{ "codex-pet": \{ candidatesByRow, captureCache: encodedCachePlan \} \}/);
  assert.match(mapper, /id="previewPause"/);
  assert.match(mapper, /id="previewResume"/);
  assert.match(mapper, /id="previewRestart"/);
  assert.match(mapper, /id="previewSpeed"/);
  assert.match(mapper, /id="previewLoop"/);
  assert.match(mapper, /function pauseSourcePreview\(\)/);
  assert.match(mapper, /function resumeSourcePreview\(\)/);
  assert.match(mapper, /function restartSourcePreview\(\)/);
  assert.match(mapper, /function updateSourcePreviewSettings\(\)/);
  assert.doesNotMatch(mapper, /rendererPreviewCommand/);
  assert.match(mapper, /sourcePreviewTickerEnabled/);
  assert.match(mapper, /liveModel\.update\(deltaMs \* sourcePreviewSpeed\)/);
  assert.match(mapper, /motionManager\.on\("motionFinish"/);
  assert.match(mapper, /id="installCodex"/);
  assert.match(mapper, /id="installClawd"/);
  assert.match(mapper, /id="chooseCodexInstallRoot"/);
  assert.match(mapper, /id="chooseClawdInstallRoot"/);
  assert.match(mapper, /confirmInstall: true/);
  assert.match(mapper, /async function prepareClawdPreview\(artifact, generation\)/);
  assert.match(mapper, /zipApi\.configure\(\{ useWebWorkers: false \}\);[\s\S]*new zipApi\.ZipReader/);
  assert.match(mapper, /function startClawdPreview\(artifact\)/);
  assert.match(mapper, /void prepareClawdPreview\(artifact, generation\)/);
  assert.doesNotMatch(mapper, /await prepareClawdPreview\(desktopArtifact\)/);
  assert.match(mapper, /id="clawdTargetPreview"/);
  assert.match(mapper, /id="clawdPreviewState"/);
  assert.match(mapper, /data-i18n-alt="preview\.clawd\.alt"/);
  assert.match(mapper, /@pixi\/unsafe-eval\/dist\/browser\/unsafe-eval\.min\.js/);
  assert.match(mapper, /connect-src 'self' blob: http:\/\/127\.0\.0\.1:\*/);
  assert.match(mapper, /function buildPreviewFiles\(files, modelFile, cubism, modelJson\)/);
  assert.match(mapper, /let activeLive2dAdapter = null/);
  assert.match(mapper, /function activateLive2dAdapter\(kind\)/);
  assert.match(mapper, /function ensureLive2dAdapter\(kind\)/);
  assert.match(mapper, /await ensureLive2dAdapter\(cubism === 2 \? "legacy" : "modern"\)/);
  assert.match(mapper, /function restorePersistedRuntimes\(\)/);
  assert.match(mapper, /function subscribeBuildProgress\(\)/);
  assert.match(mapper, /function beginBuildProgress\(target/);
  assert.match(mapper, /function setBuildProgressCapture\(target/);
  assert.match(mapper, /Live2PetBuildProgress\.progressPercent/);
  assert.match(mapper, /completedCaptureFrames \+ completed/);
  assert.match(mapper, /function handleBuildProgress\(event\)/);
  assert.match(mapper, /function requestBuildCancellation\(target\)/);
  assert.match(mapper, /typeof api\.cancelBuild/);
  assert.match(mapper, /id="cancelCodexBuild"/);
  assert.match(mapper, /id="cancelClawdBuild"/);
  assert.match(mapper, /BUILD_CANCELLED/);
  assert.match(mapper, /async function compressClawdChunk\(bytes, width, height, startFrame, frameCount\)/);
  assert.match(mapper, /<script src="\.\/clawd-capture-plan\.js"><\/script>/);
  assert.match(mapper, /<script src="\.\.\/\.\.\/packages\/clawd-target\/src\/profile\.js"><\/script>/);
  assert.match(mapper, /<script src="\.\.\/\.\.\/packages\/codex-target\/src\/profile\.js"><\/script>/);
  assert.match(mapper, /const CLAWD_PROFILE = window\.Live2PetTargetProfiles\?\.clawd/);
  assert.match(mapper, /const CODEX_PROFILE = window\.Live2PetTargetProfiles\?\.codexPet/);
  assert.match(mapper, /const CODEX_ATLAS = CODEX_PROFILE\.atlas/);
  assert.match(mapper, /Live2PetClawdCapture\.createClawdCapturePlan/);
  assert.match(mapper, /liveModel\.autoUpdate = false/);
  assert.match(mapper, /liveModel\.update\(index === 0 \? 1 : plan\.stepMs\)/);
  assert.ok((mapper.match(/liveModel\.elapsedTime = performance\.now\(\);/g) || []).length >= 2);
  assert.match(mapper, /CLAWD_CAPTURE_COMPRESSION_REQUIRED/);
  assert.match(mapper, /async function persistCaptureCacheEntry\(/);
  assert.match(mapper, /delete captures\[motionId\]/);
  assert.match(mapper, /encodingConcurrency: Live2PetClawdCapture\.resolveClawdEncodingConcurrency/);
  assert.doesNotMatch(mapper, /maxFrames/);
  assert.match(mapper, /async function retrieveDesktopArtifact\(api, artifact, target, setStatus, signal = null\)/);
  assert.match(mapper, /getBuildArtifact\(artifact\.artifactId, offset\)/);
  assert.match(mapper, /build\.progress\.stage\.transfer/);
  assert.match(mapper, /new zipApi\.BlobReader\(artifact\.blob\)/);
  assert.match(mapper, /async function loadClawdPreviewAsset\(preview, file\)/);
  assert.match(mapper, /preview: build\.preview \|\| null/);
  assert.match(mapper, /function playClawdBehaviorScenario/);
  assert.match(mapper, /id="clawdPreviewScenario"/);
  assert.match(mapper, /id="clawdPreviewTimeline"/);
  assert.match(mapper, /preview\.behavior\.scenarios/);
  assert.match(mapper, /rgbaDeflate/);
  assert.match(mapper, /motion-completed/);
  assert.match(mapper, /subscribeBuildProgress\(\);/);
  assert.match(mapper, /build\.progress\.stage\.currentCount/);
  assert.match(mapper, /id="codexBuildProgressBar"/);
  assert.match(mapper, /id="clawdBuildProgressBar"/);
  assert.match(mapper, /id="clearSavedRuntimes"/);
  assert.doesNotMatch(mapper, /refreshSkillStatus|installSkill|desktopSkillApi|Mapper Session|mapperSession/);
  assert.match(mapper, /id="chooseRuntime"/);
  assert.match(mapper, /id="chooseRuntimeFolder"/);
  assert.match(mapper, /id="runtimeFolderInput"[^>]+webkitdirectory/);
  assert.match(mapper, /function localDirectoryPath\(file\)/);
  assert.match(mapper, /async function findRuntimeEntrypoint\(files\)/);
  assert.match(mapper, /detectRuntimeKind\(await file\.text\(\)\)/);
  assert.match(mapper, /function detectRuntimeKind\(source\)/);
  assert.doesNotMatch(mapper, /id="chooseModernRuntime"|id="chooseLegacyRuntime"/);
  assert.match(mapper, /const RUNTIME_DB_NAME = "live2pet-mapper-runtime"/);
  assert.match(mapper, /const DESKTOP_RUNTIME_ORIGIN = "live2pet-runtime:\/\/library"/);
  assert.match(mapper, /async function loadDesktopRuntimeLibrary\(settings = null/);
  assert.match(mapper, /if \(desktopRuntimeApi\(\)\) \{[\s\S]*await loadDesktopRuntimeLibrary\(\);[\s\S]*return;[\s\S]*\}[\s\S]*await restorePersistedRuntimes\(\);/);
  assert.match(mapper, /if \(api\) \{[\s\S]*api\.configureRuntime\(\{ inputPath \}\)[\s\S]*await loadDesktopRuntimeLibrary\(response\.result/);
  assert.match(mapper, /await ensureDesktopRuntimeForGeneration\(cubism\);/);
  assert.match(mapper, /bridge\.getFilePath\(file\)/);
  assert.match(mapper, /function sourcePreviewAvailable\(\)/);
  assert.match(mapper, /return Boolean\(liveModel\)/);
  assert.doesNotMatch(mapper, /id="openRendererPreview"|id="restartRendererPreview"|id="closeRendererPreview"/);
  assert.doesNotMatch(mapper, /function rendererPreviewAvailability\(\)|function rendererPreviewSource\(\)/);
  assert.doesNotMatch(mapper, /runtime\.preview\.|preview\.status\.isolatedOnly/);
  assert.match(mapper, /const I18n = \(\(\) =>/);
  assert.match(mapper, /id="languageSelect"/);
  assert.match(mapper, /class="mapping-scroll"/);
  assert.match(mapper, /\.mapping-panel \{ display: flex; flex-direction: column; max-height: min\(820px, calc\(100dvh - 190px\)\); \}/);
  assert.match(mapper, /\.mapping-scroll \{ min-height: 0; overflow-y: auto; overflow-x: hidden;/);
  assert.match(mapper, /\.motion-list, \.expression-list \{ display: grid; grid-template-columns: 1fr;/);
  assert.doesNotMatch(mapper, /id="scenarioTabs"|id="startScenario"|START_SCENARIO|SCENARIO_STEP/);
  assert.doesNotMatch(mapper, /id="jsonOutput"|id="copyJson"|id="downloadJson"|live2pet-motion-map\.json/);
});

test('shared Mapper exposes project recovery, source review, and build-gate seams', () => {
  const mapper = fs.readFileSync(path.resolve(root, '../mapper/index.html'), 'utf8');
  assert.match(mapper, /function buildProjectDocument\(\)/);
  assert.match(mapper, /function parseProjectDocument\(textValue\)/);
  assert.match(mapper, /autosave/i, 'Mapper should expose an autosave or recovery entrypoint.');
  assert.match(mapper, /relink/i, 'Mapper should expose a source relink entrypoint.');
  assert.match(mapper, /sourceReview/i, 'Mapper should carry source-review state into the UI.');
  assert.match(mapper, /PROJECT_REVIEW_REQUIRED|review[^\n]{0,80}before[^\n]{0,80}build/i, 'Mapper should enforce review before a Package Build.');
  assert.match(mapper, /const PROJECT_DRAFT_STORAGE_KEY = "live2pet-mapper-project-draft-v1"/);
  assert.match(mapper, /const PROJECT_HISTORY_LIMIT = 100/);
  assert.match(mapper, /const PROJECT_EDIT_ACTIONS = new Set/);
  assert.match(mapper, /function recipeIdFor\(motionId, expressionId/);
  assert.match(mapper, /type:"ASSIGN_SELECTED_RECIPE"/);
  assert.match(mapper, /recipeMappings/);
  assert.match(mapper, /function recipeExpressionByMotion\(target\)/);
  assert.match(mapper, /function captureProjectHistoryState\(source = state\)/);
  assert.match(mapper, /function undoProjectEdit\(\)/);
  assert.match(mapper, /function redoProjectEdit\(\)/);
  assert.match(mapper, /id="undoProject"/);
  assert.match(mapper, /id="redoProject"/);
  assert.match(mapper, /window\.addEventListener\("keydown"/);
  assert.match(mapper, /project\.undo\.title/);
  assert.match(mapper, /project\.history\.status/);
  assert.match(mapper, /function restoreProjectDraft\(\)/);
  assert.match(mapper, /id="recoverProject"/);
  assert.match(mapper, /id="projectReview"/);
  assert.match(mapper, /id="ackSourceReview"/);
  assert.match(mapper, /function relinkSource\(\)/);
  assert.match(mapper, /window\.addEventListener\("beforeunload"/);
  assert.match(mapper, /if \(state\.sourceReview\?\.required\) return \{ ready: false/);
});
